# O preload ainda é necessário para carregar a imagem na memória
preload = /home/disfigured/wallpaper/wallpaper3.jpg

wallpaper {
    monitor = eDP-1
    path = /home/disfigured/wallpaper/moonpaper.jpg
    # 'cover' preenche a tela toda sem sobrar bordas
    fit_mode = cover
}

# Opcional: manter o IPC ligado para comandos em tempo real
ipc = on
splash = false
