# ~/.config/hypr/hyprlock.conf

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/wallpaper/moonpaper.jpg
    blur_passes = 0
    blur_size = 0
}

input-field {
    monitor =
    size = 400, 40
    outline_thickness = 0
    
    outer_color = rgba(0, 0, 0, 0)   # invisível
    inner_color = rgba(0, 0, 0, 0)   # invisível
    
    font_color = rgb(255, 255, 255)
    font_size = 28
    font_family = Noto Sans

    # Asteriscos brancos grandes — igual ao tema
    dots_size = 0.9
    dots_spacing = 0.4
    dots_center = true

    fail_color = rgb(255, 0, 0)   # continua branco no erro
    fail_text =                        # sem texto de erro
    
    placeholder_text =
    hide_input = false

    position = 0, 0
    halign = center
    valign = center

    rounding = 0
}

